name: Unit Tests
on:
  workflow_dispatch:

jobs:
  node-tests:
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - "14"
          - "16"
          - "18"
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      NPM_CONFIG_UNSAFE_PERM: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Pin npm registry to release date
        run: npm config set registry "https://:2023-03-20T16%3A10%3A31.107Z@time-machines-npm.sealsecurity.io/"

      - run: npm install -g npm@latest

      - name: restore lerna
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            package-lock.json
            packages/*/node_modules
            packages/*/package-lock.json
            experimental/packages/*/node_modules
            experimental/packages/*/package-lock.json
          key: node-tests-${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('package.json', 'packages/*/package.json', 'experimental/packages/*/package.json') }}-04292022

      - name: Bootstrap
        run: |
          npm install --ignore-scripts
          npx lerna bootstrap --no-ci --hoist --nohoist='zone.js' --ignore @opentelemetry/selenium-tests

      - name: Build 🔧
        run: |
          npm run compile

      - name: Unit tests
        run: |
          # TODO(legendecas): webpack https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
          if [ "${{ matrix.node_version }}" = "18" ]; then
            export NODE_OPTIONS=--openssl-legacy-provider
          fi
          npm run test

      - name: Pack artifact 📦
        if: ${{ matrix.node_version == '18' }}
        run: |
          mkdir -p /tmp/build_output
          npm pack --pack-destination=/tmp/build_output
          mv /tmp/build_output/opentelemetry-core-1.10.1.tgz /tmp/build_output/core-1.10.1.tgz
        working-directory: ./packages/opentelemetry-core

      - name: Upload artifact
        if: ${{ matrix.node_version == '18' }}
        uses: actions/upload-artifact@v4
        with:
          name: npm-tarball
          path: /tmp/build_output/core-1.10.1.tgz
          if-no-files-found: error
  node-windows-tests:
    runs-on: windows-latest
    timeout-minutes: 45
    env:
      NPM_CONFIG_UNSAFE_PERM: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Pin npm registry to release date
        run: npm config set registry "https://:2023-03-20T16%3A10%3A31.107Z@time-machines-npm.sealsecurity.io/"

      - run: npm install -g npm@latest

      - name: restore lerna
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            package-lock.json
            packages/*/node_modules
            packages/*/package-lock.json
            experimental/packages/*/node_modules
            experimental/packages/*/package-lock.json
          key: node-windows-tests-${{ runner.os }}-${{ hashFiles('package.json', 'packages/*/package.json', 'experimental/packages/*/package.json') }}

      - name: Bootstrap
        run: |
          npm install --ignore-scripts
          npx lerna bootstrap --no-ci --hoist --nohoist='zone.js' --ignore @opentelemetry/selenium-tests

      - name: Build 🔧
        run: |
          npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"
          npm run compile

      - name: Unit tests
        run: npm run test
  browser-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      NPM_CONFIG_UNSAFE_PERM: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Pin npm registry to release date
        run: npm config set registry "https://:2023-03-20T16%3A10%3A31.107Z@time-machines-npm.sealsecurity.io/"

      - name: restore lerna
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            package-lock.json
            packages/*/node_modules
            packages/*/package-lock.json
            experimental/packages/*/node_modules
            experimental/packages/*/package-lock.json
          key: browser-tests-${{ runner.os }}-${{ hashFiles('package.json', 'packages/*/package.json', 'experimental/packages/*/package.json') }}-04292022

      - name: Bootstrap
        run: |
          npm install --ignore-scripts
          npx lerna bootstrap --no-ci --hoist --nohoist='zone.js' --ignore @opentelemetry/selenium-tests

      - name: Build 🔧
        run: |
          npm run compile

      - name: Unit tests
        run: npm run test:browser
  webworker-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      NPM_CONFIG_UNSAFE_PERM: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Pin npm registry to release date
        run: npm config set registry "https://:2023-03-20T16%3A10%3A31.107Z@time-machines-npm.sealsecurity.io/"

      - name: restore lerna
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            package-lock.json
            packages/*/node_modules
            packages/*/package-lock.json
            experimental/packages/*/node_modules
            experimental/packages/*/package-lock.json
          key: webworker-tests-${{ runner.os }}-${{ hashFiles('package.json', 'packages/*/package.json', 'experimental/packages/*/package.json') }}-04292022

      - name: Bootstrap
        run: |
          npm install --ignore-scripts
          npx lerna bootstrap --no-ci --hoist --nohoist='zone.js'

      - name: Build 🔧
        run: |
          npm run compile

      - name: Unit tests
        run: npm run test:webworker
  api-eol-node-test:
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - "8"
          - "10"
          - "12"
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Pin npm registry to release date
        run: npm config set registry "https://:2023-03-20T16%3A10%3A31.107Z@time-machines-npm.sealsecurity.io/"

      - name: Build
        working-directory: ./api
        run: |
          npm install --ignore-scripts
          npm install @types/mocha@^7 mocha@^7 ts-loader@^8 ts-mocha@^8
          node ../scripts/version-update.js
          ./node_modules/.bin/tsc --build tsconfig.json tsconfig.esm.json

      - name: Test
        working-directory: ./api
        run: npm test
